### ISSUE TITLE
The parameter DBClusterIdentifier is not a valid identifier

### ISSUE THREAD

**Issue by karmux** [sst/sst#1702] opened 2022-05-17 16:35 UTC
This stack code

```
    new RDS(stack, "RDS", {
        defaultDatabaseName: "myservice",
        engine: "postgresql10.14",
    });
```

gives

```
arn-aws-iam--123456789012-root-myapp-MyServiceStack | CREATE_FAILED | AWS::RDS::DBCluster | RDSCluster073E86B4 | The parameter DBClusterIdentifier is not a valid identifier. Identifiers must either be an ARN or begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 4ad0b740-d874-462d-8b7a-aa37b385b4d4; Proxy: null)
```

when I start or deploy.

Need to add

```
cdk: {
    cluster: {
        clusterIdentifier: "myservice",
    },
},
```

to fix this error.

**Comment by fwang** [comment] 2022-06-09 06:01
Hey @karmux, that's really weird. I'm not able to reproduce this on my end.

Can you give this a try:
- temporarily remove setting `clusterIdentifier` in the code;
- run `sst build`;
- go into `.build/cdk.out`
- send me the CloudFormation template JSON file for this stack

**Comment by fwang** [comment] 2022-06-09 06:04
As a side note, it seems you are using a very length stage name `arn-aws-iam--123456789012-root`. Can you try using something shorter, ie. `karmux` and see if the error persist?

**Comment by thdxr** [comment] 2024-10-21 19:06
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 19:06 UTC
