### ISSUE TITLE
Local environment files are not used

### ISSUE THREAD

**Issue by 0ptional** [sst/sst#2397] opened 2023-01-30 16:06 UTC
The `.env.*.local` files are not used. I also tried deleting non-local files. But even then it does not work. Is it a bug or do I have to do something to enable support for it? Non-local and also stage dependent env files are used correctly.

SST Version: SST v2.0.0-rc.56

**Comment by estyrke** [comment] 2023-01-31 10:22
Works for me (in rc56). But I think the fix is pretty recent. I have only tried `.env.local`, not any other variant. Actually, I just tried `.env.<stage>.local`, and it doesn't work. Not sure if it's intended or not.

**Comment by manurana** [comment] 2023-02-07 08:04
Not working with both  `.env.local` and `.env.*.local` in SST v2.0.1
Works if I copy the vars to `.env`

**Comment by moochannel** [comment] 2023-02-16 04:50
I created a new project with SST v2.0.23, created environment variables with the same name and different values in the `.env`, `.env.local`, `.env.dev`, and `.env.dev.local` files then tried running `yarn build --stage=dev`, only `.env.dev.local` did not work.

I think it is because `dotenv.config()` is not used to read `.env.<stage>.local`.

packages/sst/src/project.ts L141
```typescript
  ProjectContext.provide(project);
  dotenv.config({
    path: path.join(project.paths.root, `.env.${project.config.stage}`),
    override: true,
  });
```

should be
```typescript
  ProjectContext.provide(project);
  dotenv.config({
    path: path.join(project.paths.root, `.env.${project.config.stage}`),
    override: true,
  });
  dotenv.config({
    path: path.join(project.paths.root, `.env.${project.config.stage}.local`),
    override: true,
  });
```

**Comment by jayair** [comment] 2023-02-17 00:20
Let me ask Dax to take a look and then can you submit a PR with this @moochannel?

**Comment by thdxr** [comment] 2023-02-17 00:38
Yep looks good can you submit a PR?

**Comment by moochannel** [comment] 2023-02-17 15:48
Thanks for merging my PR.
I will leave the repository I used for the reproduction here: [moochannel/sst-repro-dotenv](https://github.com/moochannel/sst-repro-dotenv)

**Comment by thdxr** [comment] 2024-10-21 18:16
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:16 UTC
