### ISSUE TITLE
NextJS website with Config.Parameters fails on deploy

### ISSUE THREAD

**Issue by Gr33nLight** [sst/sst#3270] opened 2023-08-30 11:28 UTC
Issue documented here https://discord.com/channels/983865673656705025/1146065148302348288

To summarise, the issue is linked to the static generation step of the Next webite. If an api route or page uses a Config.parameter, the build fails because the Config.Parameter does not exist yet if its the first deployment of the website. Parameter creation should happen prior to statically generating the NextJS pages with next build command.

**Comment by jayair** [comment] 2023-08-31 21:50
Have you read this? https://docs.sst.dev/constructs/NextjsSite#resource-binding-and-ssg

**Comment by Gr33nLight** [comment] 2023-09-04 22:18
Yes, my package.json is setup with these scripts and i run the command ` pnpm run deploy --stage prod  `: 

``` 
 "scripts": {
    "dev": "sst bind next dev",
    "dev-inspect": "sst bind NODE_OPTIONS='--inspect' next dev",
    "build": "sst bind next build",
    "deploy": "sst deploy",
    "start": "sst bind next start",
    "lint": "next lint",
    "lint-fix": "yarn run eslint --fix ./",
    "prepare": "husky install"
  },
```

The application fails on the api page.


```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
- info Linting and checking validity of types  
- info Collecting page data ..Error: Cannot use Config.STRIPE_SECRET. Please make sure it is bound to this function.
    at Object.get (/Users/gr33n/Documents/Dev/JS/emy/.next/server/chunks/6688.js:46424:27)
    at /Users/gr33n/Documents/Dev/JS/emy/.next/server/chunks/1257.js:25:137
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

> Build error occurred
Error: Failed to collect page data for /api/create-checkout-session
    at /Users/gr33n/Documents/Dev/JS/emy/node_modules/.pnpm/next@13.4.19_@babel+core@7.22.5_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1158:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}

```

**Comment by Gr33nLight** [comment] 2023-09-04 22:41
Also I checked with `pnpm sst secrets list --stage prod` and the mentioned secret is present in the list

**Comment by Gr33nLight** [comment] 2023-09-12 20:04
Yes, I do, it is a Config.Secret

**Comment by fwang** [comment] 2023-09-13 23:41
Hey @Gr33nLight I'm a little confused. It seems `Config.Secret` and `Config.Parameter` were use interchangeably in this thread and the Discord thread.

If you are binding a `Config.Secret`, as long as the secret is set for the correct stage, `sst bind next build` should pull in the secret value.

**Comment by lunsdorf** [comment] 2023-10-18 10:19
Hi there. We run into this issue as well. It happens every time we bind new `Config.Secret`s to our `NextjsSite`. As already mentioned, this happens when Next.JS generates the static pages.

```txt
- info Compiled successfully
- info Linting and checking validity of types...
- info Collecting page data...
- info Generating static pages (0/5)
- info Generating static pages (1/5)
Error: Cannot use Config.MY_NEWLY_ADDED_SECRET. Please make sure it is bound to this function.
```

There is a place in CloudFormation's stack file that seems to cause this issue:

```jsonc
"myServerFunction1234": {
   "Type": "AWS::Lambda::Function",
   "Properties": {
    "Description": "Next.js server",
    // ...
    "Environment": {
     "Variables": {
      // ...
      // The following entry is missing in the deployed stack but somehow expected when building for a
      // new deployment. Manually adding the the value and updating the stack on AWS resolves the issue.
      "SST_Secret_value_MY_NEWLY_ADDED_SECRET": "__FETCH_FROM_SSM__",
     }
    },
    "Handler": "nextjssite-index.handler",
    // ...
```

Deleting and re-creating the stack also resolves the issue. We also tried to fake the environment variable and setting `SST_Secret_value_MY_NEWLY_ADDED_SECRET` in our SST setup, but that leads to a whole new set of errors. We currently use Next.js v13.4.12 and OpenNext v2.2.3.

We just started using SST so I don't know where to look for a fix myself. Hope this helps to tackle the issue.

**Comment by jayair** [comment] 2023-10-21 00:51
Hmm are you using SSG? @lunsdorf

**Comment by lunsdorf** [comment] 2023-10-24 10:19
@jayair not explicitly. We use server components and these get statically generated when nextjs optimizes the build. There is nothing special in our `next.config.js`:

```js

export default {
  poweredByHeader: false,
  reactStrictMode: true,
  swcMinify: true,
  trailingSlash: true,
  },
};
```

**Comment by jayair** [comment] 2023-10-25 00:11
Hmm does this help? https://docs.sst.dev/constructs/NextjsSite#resource-binding-and-ssg

**Comment by matt1as** [comment] 2023-11-07 15:39
I get the same behavior, also when trying to use Config.Secrets. I'm also using DynamoDB in my SSG, so I know the Bind works. If I first run `npx sst dev --stage dev` it creates my stage and, and I can den build it using `npx sst run build --stage dev`

**Comment by jayair** [comment] 2023-11-08 00:51
Yeah we'll need to try and improve the SSG flow.

**Comment by matt1as** [comment] 2023-11-08 07:43
For me the workaround is to first create the stage using `npx sst dev --stage <stagename>` , but it would be good not to have to do that, to be able to use PullRequest stages etc.

**Comment by lunsdorf** [comment] 2023-11-08 07:48
> Hmm does this help? https://docs.sst.dev/constructs/NextjsSite#resource-binding-and-ssg

Sorry @jayair, I missed your question. Binding generally works. The issue occurs whenever we introduce a new Secret or Parameter to the application.

**Comment by blakemulnix** [comment] 2023-11-26 19:02
Also just ran into this issue and `sst bind next build` doesn't solve the issue. 

To get deployed I removed the usage of the new secret, deploy, add back in the usage of the new secret, and redeployed successfully.

**Comment by blakemulnix** [comment] 2023-11-26 19:21
I just tried this again to be sure and it did fail. So here's another replication if it helps:

Here's my the relevant chunk of my `sst.config.ts` file:

```typescript
const AWS_ACCESS_KEY_ID = new Config.Secret(stack, "AWS_ACCESS_KEY_ID");
const AWS_SECRET_ACCESS_KEY = new Config.Secret(stack, "AWS_SECRET_ACCESS_KEY");
const AWS_REGION = new Config.Secret(stack, "AWS_REGION");
const NEW_SECRET = new Config.Secret(stack, "NEW_SECRET");

const site = new NextjsSite(stack, "BlogSite", {
  customDomain: {
    domainName: rootDomain,
    domainAlias: wwwDomain,
    hostedZone: hostedZone,
  },
  bind: [blogPostBucket, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, NEW_SECRET],
});
 ```

Here's my deployment script:

```
npx sst secrets set --stage $environment AWS_ACCESS_KEY_ID $awsAccessKeyId
npx sst secrets set --stage $environment AWS_SECRET_ACCESS_KEY $awsSecretAccessKey
npx sst secrets set --stage $environment AWS_REGION $awsRegion
npx sst secrets set --stage $environment NEW_SECRET $newSecret

npx sst deploy --stage $environment
```

And here is the output of that script:

```bash
✔  Setting "AWS_ACCESS_KEY_ID"
✔  Reloaded 1 site
✔  Setting "AWS_SECRET_ACCESS_KEY"
✔  Reloaded 1 site
✔  Setting "AWS_REGION"
✔  Reloaded 1 site
✔  Setting "NEW_SECRET"
SST v2.36.6

➜  App:     blog
   Stage:   test
   Region:  us-east-1
   Account: ----

Next.js v14.0.3
OpenNext v2.3.1

┌─────────────────────────────────┐
│ OpenNext — Building Next.js app │
└─────────────────────────────────┘

yarn run v1.22.19
$ sst bind next build
Using local IAM credentials since `sst dev` is not running.

   ▲ Next.js 14.0.3
   - Environments: .env.local

 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (3/4)  [==  ] 
Error: Cannot use Config.NEW_SECRET. Please make sure it is bound to this function.
    at Object.get (/workspaces/blakemulnix-io/blog/.next/server/app/page.js:33:51210)
    at f (/workspaces/blakemulnix-io/blog/.next/server/app/page.js:33:49236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Cannot use Config.NEW_SECRET. Please make sure it is bound to this function.
    at Object.get (/workspaces/blakemulnix-io/blog/.next/server/app/page.js:33:51210)
    at f (/workspaces/blakemulnix-io/blog/.next/server/app/page.js:33:49236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot use Config.NEW_SECRET. Please make sure it is bound to this function.
    at Object.get (/workspaces/blakemulnix-io/blog/.next/server/app/page.js:33:51210)
    at f (/workspaces/blakemulnix-io/blog/.next/server/app/page.js:33:49236)
 ✓ Generating static pages (4/4) 

> Export encountered errors on following paths:
        /page: /
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:internal/errors:866
  const err = new Error(message);
              ^

Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at buildNextjsApp (file:///home/node/.npm/_npx/5e5e2f11d04ee7cb/node_modules/open-next/dist/build.js:107:8)
    at build (file:///home/node/.npm/_npx/5e5e2f11d04ee7cb/node_modules/open-next/dist/build.js:25:11)
    at file:///home/node/.npm/_npx/5e5e2f11d04ee7cb/node_modules/open-next/dist/index.js:9:1
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 152443,
  stdout: null,
  stderr: null
}

Node.js v20.9.0

Error: There was a problem building the "BlogSite" site.

Need help with this error? Post it in #help on the SST Discord https://sst.dev/discord
```

Note yarn is using `sst bind next build` not just `next build`.

**Comment by blakemulnix** [comment] 2023-12-09 17:07
@jayair Here is a [repo](https://github.com/blakemulnix/sst-bind-bug-repro) I created to reproduce. I left the steps I took in the README for ya'll.

**Comment by jayair** [comment] 2023-12-13 00:59
@blakemulnix Oh I appreciate the really detailed steps. That helped.

I noticed you weren't running `sst dev` as a part of dev workflow. Is that right?

**Comment by blakemulnix** [comment] 2023-12-13 02:35
No problem, glad to help. SST is awesome. 👍🏻

So I'm running `yarn dev` which is running `sst bind next dev`. That's early on in the readme on that repo. 

I could give running `sst dev` a shot tomorrow.

If that works, there is still the issue of the deployment not working on one go. You have to add config construct to sst config, deploy, and then add config use in the code (also shown in that repo readme).

**Comment by jayair** [comment] 2023-12-16 02:19
Yeah I think the deploy one has some workarounds but this is a limitation with SST (and CDK) currently. It effectively needs a double deploy.

We are working on fixing this properly with the new version of SST we are working on.

But yeah for dev you need `sst dev` running.

**Comment by jplwood** [comment] 2024-01-22 19:52
@jayair So just to try and summarize the workaround here: 

When you add a new parameter to an app that executes code during the build (e.g., SSG or _any_ Next.js site) you cannot use the new Parameter or Secret in your application until it has been deployed to _all_ of your stages. 

The workaround for these apps is to do `sst dev` prior to the `sst deploy` _per stage_ to ensure that stage's has latest up to date params/secrets. Does that sound right?

**Comment by jayair** [comment] 2024-01-24 00:23
Btw this isn't just a Config related issue, it applies to any bit of SST infrastructure that your Next.js app is bound to. This is fundamentally how RSC (app router) works. We talked about roughly this recently — https://twitter.com/thdxr/status/1749119186540892208.

The bad news is that something like CDK or CloudFormation cannot deal with this in a single deploy. And yeah it is a pretty severe limitation. This wasn't as big of a deal prior to app router but it is now.

The good news is that we are moving away from CDK (for this reason and a dozen others). Recently [we posted a demo](https://github.com/sst/demo-ai-app) of an app we built with [Ion](https://github.com/sst/ion).

So stay tuned, we should have something for this in a couple of weeks.

**Comment by Itsthatotherguy** [comment] 2024-03-01 05:17
I keep running into this problem as well and it seems to only be solved by removing and redeploying the stack, which is semi fine during staging but obviously a no-go for prod.

Here is what I have tried:
- Deploy without the NextJS stack. The deployment succeeds and I then assume my parameters are also deployed.
- Add the NextJS stack back but then it keeps breaking the build saying that the new parameter isn't bound.

Could I trouble someone for an official workaround while we wait for Ion to be released? Would it be best to go with .env files for parameters (not Secrets)?

**Comment by jayair** [comment] 2024-03-02 01:13
Yeah that's the work around I'm recommending for now.

**Comment by Ar-Kan** [comment] 2024-03-05 04:38
I was having the same issue, but found a solution by avoiding dot notation.
Instead of `Config.KEY`, I used 

```js
Config["KEY"]
```

This avoided the resolution at build time.
Perhaps utilizing a method accessor within Config could prevent similar issues in the future.

**Comment by jayair** [comment] 2024-03-06 00:26
Oh interesting, I didn't know about that.

**Comment by SSTPIERRE2** [comment] 2024-03-12 17:34
I ran into a very similar issue for first deploys in my SST project, where in my Web stack my Nextjs app uses RDS as a bound resource as well as one Secret. All of the stacks except Web can build just fine during a first deploy, but when the Nextjs app tries to build and generate static pages it fails because it can't access the bound RDS resource, I'm assuming since it hasn't been created yet. The first deploy will never work because the web stack causes the whole process to blow up, so no stacks actually get created.

The only workaround I was able to found, as pointed out in an earlier comment, is to physically remove the stack with the Nextjs app in it from my stacks in `sst.config.ts`, then deploy the remaining stacks which works, then finally add the web stack in and deploy once more and it works since the required resources were created during the first deploy.

It would be great if we could do a first deploy like this in one shot 😅

**Comment by Ar-Kan** [comment] 2024-03-12 18:21
> I ran into a very similar issue for first deploys in my SST project, where in my Web stack my Nextjs app uses RDS as a bound resource as well as one Secret.
> 
> All of the stacks except Web can build just fine during a first deploy, but when the Nextjs app tries to build and generate static pages it fails because it can't access the bound RDS resource, I'm assuming since it hasn't been created yet. So, the first deploy will never work because the web stack causes the whole process to blow up and no stacks actually get created.
> 
> The only workaround I was able to find, as pointed out in an earlier comment, is to physically remove the stack with the Nextjs app in it from my stacks in `sst.config.ts`, then deploy the remaining stacks which works, then finally add the web stack in and deploy once more and it works since the required resources were created during the first deploy.
> 
> It would be great if we could do a first deploy like this in one shot 😅 Or if we could tell SST to defer building a certain stack until the others are created, or skip a stack altogether so we can use two separate commands to perform the two deploys.

Accessing the property with brackets was a no go?

**Comment by Grimnirobser** [comment] 2024-04-04 04:29
> I ran into a very similar issue for first deploys in my SST project, where in my Web stack my Nextjs app uses RDS as a bound resource as well as one Secret.
> 
> All of the stacks except Web can build just fine during a first deploy, but when the Nextjs app tries to build and generate static pages it fails because it can't access the bound RDS resource, I'm assuming since it hasn't been created yet. So, the first deploy will never work because the web stack causes the whole process to blow up and no stacks actually get created.
> 
> The only workaround I was able to find, as pointed out in an earlier comment, is to physically remove the stack with the Nextjs app in it from my stacks in `sst.config.ts`, then deploy the remaining stacks which works, then finally add the web stack in and deploy once more and it works since the required resources were created during the first deploy.
> 
> It would be great if we could do a first deploy like this in one shot 😅 Or if we could tell SST to defer building a certain stack until the others are created, or skip a stack altogether so we can use two separate commands to perform the two deploys.

Comment all newly added Config secrets in the code but remain those in sst.config.ts, deploy once, then uncomment and deploy once more solves the problem

**Comment by alexsorokoletov** [comment] 2024-04-27 20:54
Interesting, for some reason if I already have a stack with the fallback parameter, if I do locally 2 steps then it all works.

```
yarn sst bind --stage ephemerial-stage1 yarn sst build 
yarn sst deploy --stage ephemerial-stage1 yarn deploy --from .sst/dist/
```

Then it works 🎉 
Quirky, and for some reason `yarn sst bind --stage ephemerial-stage1 yarn sst build ` runs the `next` (or rather OpenNext) build twice 🤷 

What does not work:

```
sst deploy --stage ephemerial-stage1 yarn deploy
```

```
sst bind --stage ephemerial-stage1 yarn sst build 
sst deploy --stage ephemerial-stage1 yarn deploy
```

```
sst bind --stage ephemerial-stage1 next build
sst deploy --stage ephemerial-stage1
```

and so on.

**Comment by adlrwbr** [comment] 2024-07-09 19:50
Here's the double deployment solution I use to create PR previews:

```ts
// sst.config.ts
const myBucket = new sst.Bucket(...)

// If we want to `import ... from sst/node/x`, the Next.js build depends on other resources' deployments
// so we need to deploy the site in a second step
const deployNext = process.env.SST_FIRST_DEPLOY !== 'true'
if (deployNext) {
    const site = new sst.NextjsSite(stack, 'MySite', {
        bind: [myBucket]
    })
    stack.addOutputs({
        URL: site.url,
    })
}
```

```sh
env SST_FIRST_DEPLOY=true npx sst deploy --stage oneshot && npx sst deploy --stage oneshot
```

**Comment by thdxr** [comment] 2024-10-21 18:13
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:13 UTC
