### ISSUE TITLE
Default tags for SNS problem

### ISSUE THREAD

**Issue by brunorib0** [sst/sst#1955] opened 2022-08-16 18:28 UTC
Heyall! I'm using SST for lots of projects in Prod since early 2022, and everything's flawless so far. Yesterday our builds (for dev and PRs - prob PROD as well [haven't tested it yet]) started to break in one part of the code that was not changed in a long time.
We have a very simple SNS topic in our stack:
```
const guestEventTopic = new sst.Topic(this, 'guest-event-sns', {
    cdk: {
      topic: {
        topicName: RESOURCE.SNS.GUEST_EVENT,
      },
    },
  });
```
And since yesterday we are getting this error:
```
***stackname*** failed: Properties validation failed for resource guesteventsnsTopic1FRD23DS with message:
#/Tags/0/Key: failed validation constraint for keyword [pattern]
#/Tags/1/Key: failed validation constraint for keyword [pattern]
```

Is there any known problem around this? Or am I missing something?

----

Investigation points so far:
1 - There are only 2 default tags created for all the resources: `sst:app` and `sst:stack`.

2 - Version used:
```
"@aws-cdk/aws-apigatewayv2-alpha": "2.24.0-alpha.0",
"@aws-cdk/aws-apigatewayv2-authorizers-alpha": "2.24.0-alpha.0",
"@serverless-stack/cli": "1.2.18",
"@serverless-stack/resources": "1.2.18",
"aws-cdk-lib": "2.24.0"
```
Tried with latest versions as well, but no luck:
```   
"@aws-cdk/aws-apigatewayv2-alpha": "2.32.0-alpha.0",
"@aws-cdk/aws-apigatewayv2-authorizers-alpha": "2.32.0-alpha.0",
"@serverless-stack/cli": "1.7.0",
"@serverless-stack/resources": "1.7.0",
"aws-cdk-lib": "2.32.0"
```

3 - For local deployment, I tried to modify the library's `synth` method of the `resources/src/App.ts` and change this part of the code:
```
//cdk.Tags.of(child).add("sst:app", this.name);
//cdk.Tags.of(child).add("sst:stage", this.stage);
cdk.Tags.of(child).add("sst_app", this.name);
cdk.Tags.of(child).add("sst_stage", this.stage);
```
Since as mentioned in [the tags doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html): 
`The key name of the tag. You can specify a value that's 1 to 128 Unicode characters in length and can't be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.`
After this modification, the deployment was successful.

Error happening in Seed.run and local.

**Comment by kculmback-eig** [comment] 2022-08-16 23:22
We are running into the same error all of a sudden trying to deploy our sst app using `sst deploy` command

```
❌  Stack failed: Properties validation failed for resource ______TopicD47D1D42 with message:
#/Tags/0/Key: failed validation constraint for keyword [pattern]
#/Tags/1/Key: failed validation constraint for keyword [pattern]
```

**Comment by fwang** [comment] 2022-08-17 12:11
hmm.. taking a look!

Btw, did this start happening after updating the SST version?

**Comment by brunorib0** [comment] 2022-08-17 12:23
Hey @fwang thanks for the reply!
No, it started to happen out of the blue, nothing was changed.

Some updates regarding this: This morning, all our PRs that were blocked because of this started to go through without a problem, so the problem is not consistent at all =( Again nothing was changed, they were just sitting in there.

I'm not sure if it's something related to AWS or not by now, because yesterday I tried to deploy the application directly from cloudformation, and it worked fine. 🤔

**Comment by fwang** [comment] 2022-08-17 12:24
I'm not able to reproduce this in my test setup. The stack is really simple:
```ts
import { StackContext, Topic } from "@serverless-stack/resources";

export default function TopicStack({ stack }: StackContext) {
  const topic = new Topic(stack, "Topic");
}
```

And the generated CloudFormation template contains this SNS Topic resource. Note the tags keys are `sst:app` and `sst:stage`.
```yml
  "Topic85E630E2": {
   "Type": "AWS::SNS::Topic",
   "Properties": {
    "Tags": [
     {
      "Key": "sst:app",
      "Value": "playground"
     },
     {
      "Key": "sst:stage",
      "Value": "dev"
     }
    ],
    "TopicName": "dev-playground-Topic"
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "dev-playground-topic/Topic/Topic/Resource"
   }
  },
```

**Comment by fwang** [comment] 2022-08-17 12:28
Here's the repo if you want to give it a try https://github.com/fwang/triage-sns-tags

**Comment by brunorib0** [comment] 2022-08-17 12:35
Yeah that's very weird, our environments are doing fine today. 🤯 

Will keep an eye on this and let you know if it happens again, then I'll try with your setup as well.
Thanks @fwang

**Comment by fwang** [comment] 2022-08-17 12:50
Yeah, keep me posted. Thanks @brunorib0

**Comment by brunorib0** [comment] 2022-08-17 15:14
> was having the same problem too randomly. I was able to reproduce consistently after I added additional tags to the app in the main function. As a workaround I ended up removing the tags and that allowed me to deploy again.
> 
> ```js
> import { App } from "@serverless-stack/resources";
> import { Tags } from "aws-cdk-lib";
> 
> import { ApiStack } from "./ApiStack";
> import { AuthStack } from "./AuthStack";
> import { StorageStack } from "./StorageStack";
> 
> export default function main(app: App) {
>   app.setDefaultFunctionProps({
>     runtime: "nodejs16.x",
>     srcPath: "services",
>     bundle: {
>       format: "esm",
>     },
>   });
> 
>   Tags.of(app).add("sst-app", "summari-sst");
>   Tags.of(app).add("sst-stage", `${app.stage}`);
> 
>   // these tags are added by default and does not follow the allowed characters for tagging in aws shared resource tags
>   Tags.of(app).remove("sst:app");
>   Tags.of(app).remove("sst:stage");
> 
>   app.stack(StorageStack).stack(AuthStack).stack(ApiStack);
> }
> ```

Is it still happening for you @asqwrd ? It went back to normal for me after a day 🤯

**Comment by kculmback-eig** [comment] 2022-08-17 15:35
Our deployments are back to working today; must have been an AWS issue?

**Comment by asqwrd** [comment] 2022-08-17 15:51
i havent tested but hesitant to put it back in case it pops back up @brunorib0

**Comment by asqwrd** [comment] 2022-08-17 16:11
> > was having the same problem too randomly. I was able to reproduce consistently after I added additional tags to the app in the main function. As a workaround I ended up removing the tags and that allowed me to deploy again.
> > ```js
> > import { App } from "@serverless-stack/resources";
> > import { Tags } from "aws-cdk-lib";
> > 
> > import { ApiStack } from "./ApiStack";
> > import { AuthStack } from "./AuthStack";
> > import { StorageStack } from "./StorageStack";
> > 
> > export default function main(app: App) {
> >   app.setDefaultFunctionProps({
> >     runtime: "nodejs16.x",
> >     srcPath: "services",
> >     bundle: {
> >       format: "esm",
> >     },
> >   });
> > 
> >   Tags.of(app).add("sst-app", "summari-sst");
> >   Tags.of(app).add("sst-stage", `${app.stage}`);
> > 
> >   // these tags are added by default and does not follow the allowed characters for tagging in aws shared resource tags
> >   Tags.of(app).remove("sst:app");
> >   Tags.of(app).remove("sst:stage");
> > 
> >   app.stack(StorageStack).stack(AuthStack).stack(ApiStack);
> > }
> > ```
> 
> Is it still happening for you @asqwrd ? It went back to normal for me after a day 🤯

removing the tags actually messed up the console so that might not be the best solution.  Taking all the Tags removal code out fixes it and it looks like deploys are working for me as well with the default

**Comment by brunorib0** [comment] 2022-08-17 17:32
> Our deployments are back to working today; must have been an AWS issue?

I don't think so, because yesterday when the error was happening still, I tried to deploy directly from cloudformation with the same tags and it was deploying correctly

**Comment by asqwrd** [comment] 2022-10-11 08:34
haven't tried it but that is weird. kind of scared to put it back in case
it pops up again and blocks other devs on my team

**Comment by thdxr** [comment] 2024-10-21 18:18
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:18 UTC
