### ISSUE TITLE
No Cloudformation Distribution in Site

### ISSUE THREAD

**Issue by BelphegorPrime** [sst/sst#2919] opened 2023-05-28 06:31 UTC
Hi,

trying to migrate my nextjs application to SST but have some problems with NextjsSite.

Because haveing Domain in Route 53 I tried the setup as following
https://docs.sst.dev/constructs/NextjsSite#configuring-alternate-domain-names-route-53-domains

but in the when creating recordProps CloudFrontTarget `new route53Targets.CloudFrontTarget(site.cdk.distribution)`.
Typescript complains that `site.cdk` can be undefined and it also is undefined when printing out the value.

So I tried bootstrap own CloudFrontDistribution, but also that didn't work.

oh and running `npx sst dev` hangs on the `➜  Start Next.js: npm run dev` output even when I run `npm run dev` in another terminal window.

edit: sst version 2.10.4
edit: my sst.config.ts

```typescript
import { SSTConfig } from 'sst';
import { NextjsSite, StackContext } from 'sst/constructs';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as route53Targets from 'aws-cdk-lib/aws-route53-targets';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import { PriceClass } from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';

const domain = 'not.local.net';

const hostedZoneId = process.env.HOSTED_ZONE_ID;

if (!hostedZoneId) {
    console.error(process.env);
    throw new Error('missing env variable');
}

const env = { hostedZoneId };
console.log(env);

function Site({ stack }: StackContext) {
    console.log('stage: ', stack.stage);
    const domainName =
        stack.stage === 'prod' ? domain : `${stack.stage}.${domain}`;
    const alternateNames = stack.stage === 'prod' ? [`www.${domain}`] : [];

    const hostedZone = route53.HostedZone.fromHostedZoneAttributes(
        stack,
        'ZentraWorldZone',
        {
            hostedZoneId: env.hostedZoneId,
            zoneName: domain,
        }
    );

    const certificate = new acm.Certificate(stack, 'Certificate', {
        domainName,
        certificateName: 'Webpage Service',
        validation: acm.CertificateValidation.fromDns(hostedZone),
    });

    const bucket = new s3.Bucket(stack, 'pageBucket');
    const bucketOrigin = new origins.S3Origin(bucket);

    const cloudfrontDistribution = new cloudfront.Distribution(stack, 'Dist', {
        defaultBehavior: { origin: bucketOrigin, compress: true },
    });

    const site = new NextjsSite(stack, 'Site', {
        path: '.',
        customDomain: {
            domainName,
            alternateNames,
            cdk: {
                hostedZone,
                certificate,
            },
        },
        cdk: {
            bucket,
            distribution: {
                defaultBehavior: { origin: bucketOrigin, compress: true },
                enabled: true,
                enableIpv6: true,
                priceClass: PriceClass.PRICE_CLASS_100,
            },
        },
    });
    console.log(site.url);
    console.log(site.cdk);

    const cloudFrontTarget = new route53Targets.CloudFrontTarget(
        cloudfrontDistribution
    );
    const recordProps = {
        recordName: domainName,
        zone: hostedZone,
        target: route53.RecordTarget.fromAlias(cloudFrontTarget),
    };
    new route53.ARecord(stack, 'AlternateARecord', recordProps);
    new route53.AaaaRecord(stack, 'AlternateAAAARecord', recordProps);

    stack.addOutputs({
        SiteUrl: site.url,
    });
}

export default {
    config(_input) {
        return {
            name: 'webpage',
            region: 'us-east-1',
        };
    },
    stacks(app) {
        app.stack(Site);
    },
} satisfies SSTConfig;

```

**Comment by jayair** [comment] 2023-05-30 20:18
Can you post this on #help on Discord?

**Comment by khuezy** [comment] 2023-06-29 02:55
`site.cdk` is undefined when in `dev` mode (ie it doesn't deploy the distribution.
` Start Next.js: npm run dev` hangs by design. You'll see updated logs in that terminal when u make infra changes to invoke infra events.
`

**Comment by thdxr** [comment] 2024-10-21 18:14
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:14 UTC
