### ISSUE TITLE
prefix automatically created roles

### ISSUE THREAD

**Issue by gurkang** [sst/sst#1422] opened 2022-02-24 08:26 UTC
I need to be able to prefix any roles that are automatically created when deploying a stack and I am having trouble finding where and how to do this?

So when the `iam:CreateRole` is called on something like `arn:aws:iam::***:role/cdk-hnb659fds-cfn-exec-role-***-region` I would like it to be `arn:aws:iam::***:role/{$customPrefix}-cdk-hnb659fds-cfn-exec-role-***-region`.

Is this possible with the current SST?

**Comment by fwang** [comment] 2022-02-24 09:24
Hi @gurkang, the role you mentioned above is created by CDK as part of `cdk bootstrap` process. `cdk bootstrap` creates 3 roles and the [role names are hardcoded](https://github.com/aws/aws-cdk/blob/master/design/cdk-bootstrap.md#physical-resource-names).

The roles created in ur SST app are all prefixed by `{$stageName}-{$appName}-`, ie. `dev-my-app-`. Are you able to build the custom prefix using the stage and app name?

**Comment by gurkang** [comment] 2022-02-24 09:32
hmm, so is there any way to override those cdk bootstrapped roles? Since it's these specifically that are causing issues.

**Comment by fwang** [comment] 2022-02-24 09:48
According to the CDK team, I think the only way to do this is to create and deploy your own bootstrap CloudFormation template. So you have full flexibility over the role name. And when you create `Stacks` in your app, pass in the name of the role:
```js
new MyStack(app, "my-stack", {
  synthesizer: new DefaultStackSynthesizer({
    cloudFormationExecutionRole: "...",
    deployRoleArn: "...",
  }),
});
```

https://github.com/aws/aws-cdk/issues/5798#issuecomment-576577173

**Comment by fwang** [comment] 2022-02-24 09:53
Oh btw, you can also try running `cdk bootstrap --qualifier acme`, ur roles will be prefixed `cdk-acme-`. It still starts with `cdk-`.

**Comment by gurkang** [comment] 2022-02-24 10:04
Oh. So then I would have to abandon working with SST? Seems like such a shame

**Comment by fwang** [comment] 2022-02-24 10:21
Wait, there might some confusion. All of the above work works with SST.

**Comment by MagnusNordin** [comment] 2022-04-01 11:44
@fwang 
I think what is needed is a new parameter in this call https://github.com/serverless-stack/serverless-stack/blob/master/packages/core/src/index.ts#L179 
there is a parameter to **cdk bootstrap** called **--template**. 
Is there a way to get this changed?

**Comment by bestickley** [comment] 2022-12-05 19:26
@fwang, I think the issue is that `sst bootstrap --qualifier acme` doesn't work as expected. SST strips out the qualifier when it invokes `cdk bootstrap` itself. It would be great if `sst bootstrap` could pass all arguments that `cdk bootstrap` takes. In the mean, time you can work around this by running `cdk bootstrap --qualifier acme && sst bootstrap`.

**Comment by thdxr** [comment] 2024-10-21 19:07
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 19:07 UTC
