### ISSUE TITLE
Bug: Some functions throw "TypeError: URL is not a constructor", after being transpiled by esbuild

### ISSUE THREAD

**Issue by missbach** [sst/sst#2702] opened 2023-03-23 09:19 UTC
This issue is caused by the "banner" defined in [runtime/handlers/node.ts, line 147](https://github.com/serverless-stack/sst/blob/master/packages/sst/src/runtime/handlers/node.ts#L147).
Simplified version: `esbuild({ banner: 'const __dirname = topLevelFileUrlToPath(new URL(".", import.meta.url))'`

Esbuild is blissfully unaware of the fact that the banner uses the 'URL' global, and is therefore completely fine when imported code assignes a new value to 'URL'. For me, this happens in one of my dependencies, the ['uuid' npm package](https://www.npmjs.com/package/uuid).

Steps to reproduce:

1. Define a function with the following code, as a `.js` file and with the `package.json` configured for ESM modules:
```js
import { v3 } from 'uuid'
export const handler = () => v3()
```
2. Execute it via the SST Console. You should see `TypeError: URL is not a constructor`.

Why? The transpiled artifact contains `var URL` lexically somewhere further down, but nonetheless in the top-level scope. The variable declaration of course gets hoisted, and therefore obscures the 'URL' global that the SST banner references.

As far as I know, this bug only applies to functions packaged as ESM modules.

As a fix, my first idea would be to update the line right above it (line 146) to `import { fileURLToPath as topLevelFileUrlToPath, URL as topLevelURL } from "url"`, and then using 'topLevelURL', of course.
Still a bit messy though – what about using `require()` and wrapping everything in an anonymous function? This should minimize the possible conflict surface.

**Comment by jayair** [comment] 2023-03-24 21:43
Can you start a thread in #help on Discord and link to this? We'll look at it there.

**Comment by missbach** [comment] 2023-03-25 10:34
Done 👍 – [(Link)](https://discord.com/channels/983865673656705025/1089132870548865116)

**Comment by robsquires** [comment] 2023-03-29 14:08
`+1` for this! Having the same issue with `node-fetch`'s ESM build. fwiw as a workaround you can import the commonjs version using `require`

**Comment by robsquires** [comment] 2023-03-29 14:10
@missbach happy to help with PR if useful!

**Comment by missbach** [comment] 2023-03-29 14:40
@robsquires thanks! head over to [Discord](https://discord.com/channels/983865673656705025/1089132870548865116) for an update. fyi, we're using a custom esbuild banner to mitigate this issue, works well!

**Comment by paymonsattar** [comment] 2023-03-29 14:56
Could this also be the cause of this - https://github.com/serverless-stack/sst/issues/2635

**Comment by thdxr** [comment] 2024-10-21 18:15
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:15 UTC
