### ISSUE TITLE
Can't upload Json files to s3 buckets though local interface

### ISSUE THREAD

**Issue by NigelThorne** [sst/sst#1358] opened 2022-02-13 13:13 UTC
Uploading a file to S3 bucket using the SST localhost interface fails for JSON files.
Attempting to upload the file causes a crash. 
Renaming the file to `X.j` and it can now be uploaded.

```
SST Console: https://console.serverless-stack.com/bucket-image-resize/nwt/local
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at write_ (_http_outgoing.js:722:11)
    at ClientRequest.write (_http_outgoing.js:687:15)
    at /home/nigel/Projects/bucket-image-resize/node_modules/@serverless-stack/core/dist/runtime/server.js:110:25
    at Layer.handle [as handle_request] (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:137:13)
    at rawParser (/home/nigel/Projects/bucket-image-resize/node_modules/body-parser/lib/types/raw.js:58:7)
    at Layer.handle [as handle_request] (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:137:13)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:131:14)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:131:14)
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at write_ (_http_outgoing.js:722:11)
    at ClientRequest.write (_http_outgoing.js:687:15)
    at /home/nigel/Projects/bucket-image-resize/node_modules/@serverless-stack/core/dist/runtime/server.js:110:25
    at Layer.handle [as handle_request] (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:137:13)
    at rawParser (/home/nigel/Projects/bucket-image-resize/node_modules/body-parser/lib/types/raw.js:58:7)
    at Layer.handle [as handle_request] (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:137:13)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:131:14)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:131:14)
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Object
    at write_ (_http_outgoing.js:722:11)
    at ClientRequest.write (_http_outgoing.js:687:15)
    at /home/nigel/Projects/bucket-image-resize/node_modules/@serverless-stack/core/dist/runtime/server.js:110:25
    at Layer.handle [as handle_request] (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:137:13)
    at rawParser (/home/nigel/Projects/bucket-image-resize/node_modules/body-parser/lib/types/raw.js:58:7)
    at Layer.handle [as handle_request] (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:137:13)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:131:14)
    at next (/home/nigel/Projects/bucket-image-resize/node_modules/express/lib/router/route.js:131:14)

Error: socket hang up
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by fwang** [comment] 2022-02-15 09:27
Hey @NigelThorne, I'm not able to reproduce the issue.

May I bother you to hard refresh the console and then give it a try again? And let me know if you still see the error.

**Comment by Manitej66** [comment] 2022-03-03 16:14
Even I was not able to replicate the issue

**Comment by NigelThorne** [comment] 2022-03-04 05:56
sorry.. back.. How do I hard refresh the console ?

**Comment by NigelThorne** [comment] 2022-03-04 08:50
I upgraded to 67 and now it works. 0.63.0 had the problem.

**Comment by monika6633** [comment] 2023-04-01 16:37
https://github.com/serverless-stack/sst/issues/1358

**Comment by thdxr** [comment] 2024-10-21 19:07
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 19:07 UTC
