### ISSUE TITLE
How do I use efs?

### ISSUE THREAD

**Issue by jessekrubin** [sst/sst#453] opened 2021-06-16 21:45 UTC
How do I use efs with sst?

**Comment by fwang** [comment] 2021-06-16 22:39
Hey @jessekrubin, do you mean mounting EFS in your Lambda functions?

`sst.Function` extends CDK's `lambda.Function` construct, give this a try:
``` js
// create a new Amazon EFS filesystem
const fileSystem = new efs.FileSystem(stack, 'Efs', { vpc });

// create a new access point from the filesystem
const accessPoint = fileSystem.addAccessPoint('AccessPoint', {
  // set /export/lambda as the root of the access point
  path: '/export/lambda',
  // as /export/lambda does not exist in a new efs filesystem, the efs will create the directory with the following createAcl
  createAcl: {
    ownerUid: '1001',
    ownerGid: '1001',
    permissions: '750',
  },
  // enforce the POSIX identity so lambda function will access with this identity
  posixUser: {
    uid: '1001',
    gid: '1001',
  },
});

const fn = newsst.Function(stack, 'MyLambda', {
  handler: "src/lambda.main",
  vpc,
  // mount the access point to /mnt/msg in the lambda runtime environment
  filesystem: lambda.FileSystem.fromEfsAccessPoint(accessPoint, '/mnt/msg'),
});
```

Btw, this is based on CDK's doc - https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-readme.html#filesystem-access

Let me know if this works for you.

**Comment by jessekrubin** [comment] 2021-06-17 20:22
Works! How would I attach multiple efs volumes? I can do it through the console but I'm not sure how to do it with cdk/sst

**Comment by fwang** [comment] 2021-06-18 08:07
I think you can only mount 1 EFS volume to a Lambda function?

**Comment by jessekrubin** [comment] 2021-06-18 08:09
You can mount several from the aws console. I don't know how to do it with cdk. I have an open bug/issue/enchantment on the cdk repo asking how to do this. Would be super super nice.

**Comment by jessekrubin** [comment] 2021-06-18 08:10
https://github.com/aws/aws-cdk/issues/14885

**Comment by fwang** [comment] 2021-06-22 04:40
Just read the conversation on the CDK thread you shared above, that makes sense. Before CDK rolls out high-level support for this, you can do something like this:
```js
...
const fn = newsst.Function(stack, 'MyLambda', {
  handler: "src/lambda.main",
  vpc,
  // mount the access point to /mnt/msg in the lambda runtime environment
  filesystem: lambda.FileSystem.fromEfsAccessPoint(accessPoint, '/mnt/msg'),
});

const cfnFunction = fn.node.defaultChild as CfnFunction;
cfnFunction.addPropertyOverride("FileSystemConfigs", {
  ...
});
```

With `CfnFunction`, the syntax will be uglier, but you can pretty much do anything that ClouldFormation supports.

**Comment by villelahdenvuo** [comment] 2023-10-03 15:43
@fwang I guess this issue can be closed? Also not a bug.

**Comment by thdxr** [comment] 2024-10-21 19:10
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 19:10 UTC
Labels: bug
