### ISSUE TITLE
Using internal monorepo packages without transpilation in stacks code

### ISSUE THREAD

**Issue by DCzajkowski** [sst/sst#1915] opened 2022-07-29 17:45 UTC
## Setup

Example monorepo setup:

```
my-project/
|-- apps/
|   +-- backend/
|       |-- .build/
|           +-- index.js # built using the SST CLI, namely Stacks.build from @serverless-stack/core
|       |-- src/
|       |-- stacks/
|           +-- index.ts
|       |-- package.json
|       +-- sst.json
|-- node_modules/
|-- packages/
|   +-- core/
|       |-- index.ts
|       +-- package.json
|-- package.json
+-- yarn.lock
```

**my-project/apps/backend/package.json**
```json5
{
  // ...
  "dependencies": {
    "@my-project/core": "*"
  }
}
```

**my-project/packages/core/index.ts**
```ts
export const SOME_CONSTANT = 42
```

**my-project/apps/backend/stacks/index.ts**
```ts
import { App } from '@serverless-stack/resources'
import { SOME_CONSTANT } from '@my-project/core'

export default function main(app: App) {
  console.log(SOME_CONSTANT)

  // ...
}
```

## Problem

When you run your stacks with `sst start`, the following file will be built:

**my-project/apps/backend/.build/index.js**
```ts
// ...
import { SOME_CONSTANT } from '@my-project/core'; // This is a problem, because @my-project/core is written in TS and not transpiled at any point.
                                                  // Throws an error in runtime: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /path/to/my-project/packages/core/index.ts
//...
```

Of course this is because the stacks code, when being built using esbuild, [marks all `"dependencies"` from `package.json` as external](https://github.com/serverless-stack/sst/blob/master/packages/core/src/stacks/build.ts#L32-L34).

### The easy way

Add a configuration option to mark dependencies as "non-external", so they are built and bundled by esbuild. This is what is used by nextjs and its [next-transpile-modules](https://github.com/martpie/next-transpile-modules#examples).

### The harder way

Find out, the package is internal, as it points to a TS file (`"main"` field in `node_modules/@my-project/core/package.json`, symlinked to `my-project/packages/core/package.json` by yarn, is set to `"*.ts"`).

The hard part may be, that this can be potentially slow.

## PR

Is a PR for this welcome? Which approach should I take?

**Comment by thdxr** [comment] 2022-07-30 15:03
Thanks for the detailed writeup!

Does it work if you import it using a relative path?

**Comment by DCzajkowski** [comment] 2022-08-01 19:18
If the package uses relative imports, it would work, yes.

However, in our setup, we ban relative imports (in apps and in packages!) and rely on the package name. 

For example, in `my-project/packages/core/index.ts` we would import using `import ... from '@my-project/core/other'`, not `import ... from './other'`. (self referencing)

This is because we really like importing relative to the root, not relative to the file that has the import statement. In the above example, `@my-project/core` can be thought of as a Typescript alias for _the root of the package_.

**Comment by AshHeskes** [comment] 2022-08-10 20:07
Just to chime in and I might be wrong but the way NPM handles workspaces (monorepos) is that all "workspaces" get symlinked (not sure how it is with yarn). Thus there's no need to add a local package as a dependency. It already exists as an import reference of `import ... from "my-other-package"` based on the name in `package.json`. Thus esbuild should include it if you remove as a dependency and just `import` it (again for NPM not yarn).

**Comment by DCzajkowski** [comment] 2022-08-11 14:53
@AshHeskes yarn also symlinks, so there is no need to list it there either.

However, there are two problems with this approach:
1. You are not explicit as to which packages you are using (and which packages should be be bundled in app.asar in Electron for example).
2. The [import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) ESLint rule, if used, would fail.

**Comment by Newbie012** [comment] 2022-11-06 16:28
I'm having the same issue. Each micro-service is a different package and is exposed as `Stack`. The only solution I have in mind is to build all of the packages and then run `sst start`, but I don't think it will scale well.

Any ideas?

**Comment by thdxr** [comment] 2022-11-08 11:34
If you break things up into multiple packages you must build those packages separately.  Node cannot import TS directly from another package, it expects built code.


This is why we strongly advise against creating a lot of package boundaries.

**Comment by DCzajkowski** [comment] 2022-11-08 11:38
@thdxr What do you think about exposing a whitelist for packages that should be built, similar to [next-transpile-modules](https://github.com/martpie/next-transpile-modules#examples)?

**Comment by Newbie012** [comment] 2022-11-08 11:56
@thdxr Before I switched to sst, I built my entry package with esbuild, which transpiled all of the other TS packages. What am I missing here?

If it helps anyone, for now, I settled on the following setup:

1. [tsup](https://github.com/egoist/tsup/) for building/watching.
2. [turborepo](https://turborepo.com/) for concurrent builds and caching.

**Comment by thdxr** [comment] 2022-11-08 12:05
The issue is that is a hack around the way the module system in node and typescript works.

We're unlikely to support non-standard things like this because it breaks compatibility with other tools - we've already seen this in other cases where some non-standard code in our codebase breaks under pnpm.

To reiterate this isn't an SST issue. In the node/TS world when importing code from another package it must already be built. So you'd have to setup your own build process to build your stacks code into js first, which you can do through turborepo

We advise against this because there's no advantage to breaking things up into packages like this and you lose a bunch of typescript features like symbol renaming. We recommend using typescript path aliases to simulate a different package

**Comment by DCzajkowski** [comment] 2022-11-08 12:24
> We advise against this because there's no advantage to breaking things up into packages like this 

I agree, however in our use-case we import packages that should be packages (like our internal helpers). 
We don't want to have to build the package just for SST, if for our frontend, backend, and app we don't have to do that.

Building packages makes us lose some features like instant feedback loop, jump to definition etc.

Currently, we simply don't list the package in package.json, but that seems to be a hack. An API like next-transpile-modules seems to work much better, as you can opt-in to building specific packages on the fly.

**Comment by DCzajkowski** [comment] 2022-11-08 12:29
By the way, turborepo's `yarn create turbo` uses this setup by default, ie. their "ui" package is never built (doesn't even have builder set up nor "build" script in package.json). Both "web" and "docs" apps transpile the "ui" package on the fly with 

```js
experimental: {
  transpilePackages: ["ui"],
},
```
in `next.config.js`.

**Comment by Max101** [comment] 2023-01-30 16:51
Is there any progress on this? 
I found out the hard way that this actually works out of the box for the "Runtime" or Lambda code, but it does not work for the stacks code. So for example if I set a dependency to a package in `package.json` and the package is local, then the 

```
import { Example } from '@localPackage/example';
```

works just fine for code within Runtime, but For the hell of it I dont know how to make it work for code that lies within `stacks`.

I tried adding different `tsconfig.json` files from within both, tried referencing the package "manually" with the tsconfig `paths: {}`   option, but I keep on getting the following error: Anyone knows how to get around this? 

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ...

**Comment by jayair** [comment] 2023-02-02 10:48
@Max101 how come you want to do this in your stacks code? Do you have a really large stacks codebase?

**Comment by Max101** [comment] 2023-02-02 14:06
I have some code that is reused between source and stacks. That code is a Config-style (`@myapp/config`) package where we keep all the application config that is reused on both BE and FE applications. Some of that config also creates AWS resources on demand.
What we've done to get around this is to split the config part related to stacks out of the Config package for now, but it would be nice if this gets addressed at some point.

**Comment by thdxr** [comment] 2023-02-06 15:24
Have you tried this with sst2? I think it might just work given some of the other restructuring we did

**Comment by jayair** [comment] 2023-02-17 00:21
@paymonsattar what's your use case for this? How come you have a separate package for your stacks code?

**Comment by paymonsattar** [comment] 2023-02-17 10:56
> @paymonsattar what's your use case for this? How come you have a separate package for your stacks code?

We are using SST extensively in our company. We have a common project that is used by several other projects. In one of our projects, a private api built using SST, that utilises the common package we get the following error. This error only appears on projects that use SST.

`node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/paymon/project/backend/common/src/index.ts
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'`

This is referring to the `"main": "src/index.ts"` in common/package.json. Replacing that with `"main": "dist/index.js",
  "types": "dist/index.d.ts"` does fix the issue. But obviously, it is just a temp fix.

**Comment by thdxr** [comment] 2023-02-23 23:35
Hey @paymonsattar can you create a minimal reproduction - I think I should be able to fix this

**Comment by whimzyLive** [comment] 2023-04-27 07:24
@thdxr  this is much needed, specially in the monorepo type setup

**Comment by jayair** [comment] 2023-04-28 19:26
Well our starters are all monorepo by default. But this is for folks that are managing their own constructs. Is this what you are doing?

**Comment by JoshBarr** [comment] 2023-06-05 21:51
We've also just run into this issue. Firstly, let me say that SST is amazing, and we're rapidly adopting it at @vital-software. Thanks for making an awesome thing 😀 🎉 

In our nx monorepo, each stack lives in a separate app directory, so that nx can figure out which stacks to test and deploy via `nx affected`. This works really well, and we use it to create ephemeral stacks for our PR integration tests. 

We've reached the point where it makes sense to start extracting some common instrumentation config (logging and monitoring constructs, and some sensible defaults for lambda functions) that can be shared between stacks.

Successful workarounds so far:
- Build our common package first, and import the built artefacts into our apps
- Use a relative import in `sst.config.ts` files to import our shared constructs from the nx libs directory (`../../libs/`). 

For now, I think we're going to use relative imports. I couldn't get path aliases working with TypeScript/ESM, but that's probably PEBKAC 😅

**Comment by jayair** [comment] 2023-06-07 17:38
Ah I see thanks for sharing the details. This might be something we need to figure out. @thdxr thoughts?

**Comment by wcisco17** [comment] 2023-06-13 08:47
@jayair That would be great our company is using netlify at the moment for deployments, but we're playing around SST haven't found a good guide on NX + SST (I'd be curious to hear how @JoshBarr figured that out. 😄

**Comment by jayair** [comment] 2023-06-13 22:57
Hmm we don't have a guide but I came across this message about some NX related question today on Discord: https://discord.com/channels/983865673656705025/1027265626085019769/1118172312445919272

**Comment by closesimple-wl** [comment] 2023-09-19 14:39
Pattern that requires this: https://turbo.build/blog/you-might-not-need-typescript-project-references

**Comment by citypaul** [comment] 2023-12-31 16:18
For anybody hitting this issue, I just went ahead and use typescript aliases instead of using workspace imports in my package.json, and it worked for me.

It's a little frustrating because there's a bit of a miss-match between what the turborepo docs [recommend here](https://turbo.build/repo/docs/handbook/sharing-code/internal-packages): and this setup, but I don't think it's a very serious problem.

Just to help people who may be googling the error I had, I'm going to paste the error message here, because mine was a little different to those I've seen in the thread, but the root cause was the same:

```sh
✖  Build failed apps/lambdas/src/migrate.handler
   Could not resolve "@babel/preset-typescript/package.json"
   node_modules/.pnpm/@babel+core@7.23.7/node_modules/@babel/core/lib/config/files/module-types.js
   98 │             const packageJson = require("@babel/preset-typescript/package.json");
   No loader is configured for ".node" files: node_modules/.pnpm/fsevents@2.3.3/node_modules/fsevents/fsevents.node
   node_modules/.pnpm/fsevents@2.3.3/node_modules/fsevents/fsevents.js
   13 │ const Native = require("./fsevents.node");
```

**Comment by thdxr** [comment] 2024-10-21 18:18
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:18 UTC
