### ISSUE TITLE
bucket-image-resize example no longer working?

### ISSUE THREAD

**Issue by timmattison** [sst/sst#3495] opened 2023-11-06 15:48 UTC
Any time I try to deploy this example, with no modifications, I get the following error:

```
Error: Cannot find asset at /Users/myuser/code/bucket-image-resize/layers/sharp
       at new AssetStaging (/Users/myuser/code/bucket-image-resize/node_modules/.pnpm/aws-cdk-lib@2.101.1_constructs@10.2.69/node_modules/aws-cdk-lib/core/lib/asset-staging.js:1:2119)
       at new Asset (/Users/myuser/code/bucket-image-resize/node_modules/.pnpm/aws-cdk-lib@2.101.1_constructs@10.2.69/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.js:1:1080)
       at AssetCode.bind (/Users/myuser/code/bucket-image-resize/node_modules/.pnpm/aws-cdk-lib@2.101.1_constructs@10.2.69/node_modules/aws-cdk-lib/aws-lambda/lib/code.js:1:4881)
       at new LayerVersion (/Users/myuser/code/bucket-image-resize/node_modules/.pnpm/aws-cdk-lib@2.101.1_constructs@10.2.69/node_modules/aws-cdk-lib/aws-lambda/lib/layers.js:1:2277)
       at EmptyStack.ExampleStack (file:///Users/myuser/code/bucket-image-resize/.sst.config.1699285640685.mjs:20:13)
       at stack (file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/constructs/FunctionalStack.js:20:35)
       at App.stack (file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/constructs/App.js:494:16)
       at Object.stacks [as fn] (file:///Users/myuser/code/bucket-image-resize/.sst.config.1699285640685.mjs:45:9)
       at synthInRoot (file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/stacks/synth.js:56:24)
       at async Module.synth (file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/stacks/synth.js:19:16)
       at async build (file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/cli/commands/dev.js:157:38)
       at async file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/cli/commands/dev.js:295:13
       at async Promise.all (index 0)
       at async Object.handler (file:///Users/myuser/code/bucket-image-resize/node_modules/.pnpm/sst@2.34.7/node_modules/sst/cli/commands/dev.js:322:9)
```

To recreate:

1. `pnpm create sst --template=examples/bucket-image-resize`
2. Name the project bucket-image-resize
3. `cd bucket-image-resize`
4. `pnpm install`
5. `pnpm run dev`

Is there an obvious mistake I'm making. It works with all other examples I've tried so far.

**Comment by jayair** [comment] 2023-11-08 00:56
Btw for help on this issue, can you open a thread in #help on Discord.

**Comment by perfectbase** [comment] 2023-12-09 03:54
I'm also having a similar problem with sharp.

@timmattison I believe your error is just that you are not creating the layer folder before running deploy.
You should check out this part of the tutorial:
https://arc.net/l/quote/umkiihcz

That said, the example still doesn't work even with the layer deployed correctly.
@jayair Just to give a little more context. I have a working app in production deployed with sst using sharp to resize images. Recently I redeployed the app after changing some logs (without changing any versions or logic) and the app broke. I'm not sure if the problem is with sst, sharp, aws, or esbuild... I even tried to recreate a minimal example from scratch, but nothing I try works anymore.

I hope someone can shed a light here.
I'll also try the discord help channel.

Thank you in advance for any help!

**Comment by perfectbase** [comment] 2023-12-09 05:31
Just got support from discord and got it to work.

It seems that I was trying a broken build from the repo. https://github.com/Umkus/lambda-layer-sharp/releases
the version 0.32.6 seems to not work. When I tried version 0.32.1 everything worked as expected.

although the repo suggested in the discord thread seems more reliable: https://github.com/pH200/sharp-layer

here is what the code looks like:

```ts
  const bucket = new Bucket(stack, "Bucket", {
    notifications: {
      resize: {
        function: {
          handler: "packages/functions/src/resize.main",
          nodejs: {
            esbuild: {
              external: ["sharp"],
            },
          },
          layers: [
            new lambda.LayerVersion(stack, "SharpLayer", {
              code: lambda.Code.fromAsset("layers/sharp-0.32.3-x64.zip"),
              compatibleRuntimes: [lambda.Runtime.NODEJS_18_X],
              compatibleArchitectures: [lambda.Architecture.X86_64],
            }),
          ],
        },
        events: ["object_created"],
      },
    },
  });
```

maybe it would be a good idea to update the turorial.

**Comment by thdxr** [comment] 2024-10-21 18:12
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:12 UTC
