### ISSUE TITLE
Error synthesizing your app - policy-statement.js

### ISSUE THREAD

**Issue by aryaenterprises-cloud** [sst/sst#2214] opened 2022-11-22 07:24 UTC
Hi All,

SST Version: 1.17.1

My sst app which was running quite well is now throwing this error when running `sst deploy` and I have no clue how to investigate this further. 

```
TypeError: Cannot read properties of undefined (reading 'length')
    at D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\policy-statement.js:2:8107
    at Array.map (<anonymous>)
    at count (D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\policy-statement.js:2:8061)
    at PolicyStatement._estimateSize (D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\policy-statement.js:2:7743)
    at D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\policy-document.js:1:3377
    at Array.map (<anonymous>)
    at PolicyDocument._splitDocument (D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\policy-document.js:1:3365)
    at Role.splitLargePolicy (D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\role.js:1:9495)
    at Object.visit (D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\role.js:1:3024)
    at recurse (D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\core\lib\private\synthesis.js:1:1799)



There was an error synthesizing your app.
```

From the error above, it seems to be an issue with IAM policy - although I am not sure what I need to check ? Any help here please ?

**Comment by alistairstead** [comment] 2022-11-30 10:45
While building the CF templates, your stack code fails to compile. If it used to work, it might be that a dependency has changed the type definition since you last deployed the app. Make sure you are using the version of `aws-cdk-lib` that is compatible with SST currently version `2.20.0` I think.

Have you run `typecheck`? This will point you to where the problem and confirm if the issue is in your project code of a dependency.

**Comment by fwang** [comment] 2022-12-14 05:38
Thanks @alistairstead.

@aryaenterprises-cloud if you open up `D:\dev\agsnirmanltd-next\node_modules\aws-cdk-lib\aws-iam\lib\policy-statement.js:2:8107`, what do you see on line 2?

**Comment by thdxr** [comment] 2024-10-21 18:17
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:17 UTC
