### ISSUE TITLE
Access log retention days type 'string' is not assignable to type

### ISSUE THREAD

**Issue by roughee** [sst/sst#1774] opened 2022-06-02 11:23 UTC
I only tried this in JS it will throw a warning and will still generate correct build. 

So the example in code/docs the example is to do this (which works fine):
```
accessLog: {
  retention: "two_weeks",
},
```

The code below works fine in JS, but generates a warning.
```
let retentionTime = "two_weeks";
if (scope.stage === "prod") {
  retentionTime = "six_months";
}
<...>
accessLog: {
  retention: retentionTime,
},
```

So this will generate a warning: Type 'string' is not assignable to type '"six_months" | "two_months" | "one_day" | "three_days" | "five_days" | "one_week" | "two_weeks" | "one_month" | "three_months" | "four_months" | "five_months" | "one_year" | ... 5 more ... | "infinite"'.

This is the place that maps the string:
https://github.com/serverless-stack/serverless-stack/blob/master/packages/resources/src/util/apiGatewayV2AccessLog.ts#L128

So the fix could be to cast the string to const.
```
const retentionValue =
    logs.RetentionDays[
      retention.toUpperCase() as const as keyof typeof logs.RetentionDays
    ];
```

**Comment by fwang** [comment] 2022-06-08 01:35
Hey @roughee, I'm able to reproduce this also in TypeScript.
```ts
  let retention = "four_months";

  new Api(stack, "api", {
    accessLog: {
      retention,
    },
  });
```
Error is: `Type 'string' is not assignable to type '"four_months" | "one_day" | ...`

Looping in @thdxr, is there a less cumbersome fix?

**Comment by thdxr** [comment] 2022-06-08 14:53
this one is tricky because TS cannot infer the right type without more type info (like const) - which isn't possible in JS

Can you write it as a ternary? Eg `const retention = condition ? "two_weeks" : "six_months"`

**Comment by thdxr** [comment] 2024-10-21 18:19
We are transition this repo to https://github.com/sst/v2 and are closing this issue for now. If it is still relevant please reopen it there - sorry for the trouble

**Closed by thdxr** 2024-10-21 18:19 UTC
